server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          server:
            webmvc:
              routes:
                ### Product Service Route
                - id: product-service
                  uri: lb://product-service
                  predicates:
                    - Path=/api/products/**
                ### Inventory Service Route
                - id: inventory-service
                  uri: lb://inventory-service
                  predicates:
                    - Path=/api/products/**/inventory/**
                ### Order Service Route
                - id: order-service
                  uri: lb://order-service
                  predicates:
                    - Path=/api/products/**/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.function: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
