<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
        <groupId>top.daisyflows.shoppingwithtechie</groupId>
        <artifactId>Daisy-Shopping-With-Techie</artifactId>
        <version>0.1.0-SNAPSHOT</version>
	</parent>

	<groupId>top.daisyflows.shoppingwithtechie.business</groupId>
	<artifactId>product-service</artifactId>
	<version>0.1.0-SNAPSHOT</version>

	<name>product-service</name>
	<description>Product Service API Rest that contains business logic, MongoDB Connection and offers endpoints to Feign Connection</description>

	<properties>
		<java.version>17</java.version>
	</properties>

	<dependencies>
        <!-- Mongo DB -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb-test</artifactId>
			<scope>test</scope>
		</dependency>
        <!-- INTEGRATION TESTS DEPENDENCIES -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-mongodb</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Project Commons -->
        <dependency>
            <groupId>top.daisyflows.shoppingwithtechie</groupId>
            <artifactId>project-dtos</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>
