server:
  port: 8084

spring:
  application:
    name: inventory-service
  banner:
    location: BANNER_LOCATION.txt
    # No mostrar banner
    #main:
    #banner-mode: off
  ## MySQL BBDD Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/MSVC_Techie_Shop_Inventory?useSSL=false&serverTimeZone=UTC&allPublicKeyRetrival=true
    username: root
    password: 200548
  jpa:
    properties:
      hibernate:
        # Mostrar Mensajes SQL en Consola
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  pattern:
    dateformat: hh:mm
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
