server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

spring:
  rabbitmq:
    host: ${AMQP.HOST:localhost}
    port: ${AMQP.PORT:5672}
    username: ${AMQP.USERNAME:kadanarpa}
    password: ${AMQP.PASSWORD:200548}
  cloud:
    openfeign:
      circuitbreaker: { enabled: true }

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  # Distributed Tracing
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans

# Resilience4J Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 80
        wait-duration-in-open-state.seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      inventory:
        base-config: default

  # Resilience4j Time Limiter
  timelimiter:
    instances:
      inventory:
        timeout-duration.seconds: 3

  # Retry Properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration:
          seconds: 5

logging:
  pattern:
    dateformat: hh:mm
  level:
    root: INFO
    org.hibernate.SQL: DEBUG