name: Create Feature

on:
  workflow_dispatch:
    inputs:
      featureName:
        description: Feature Branch name with a Jira KEY
        required: true
        type: string

jobs:
  call-feature-workflow:
    permissions:
      contents: write
    uses: kadanarpaOps/Ops-Github-Workflows/.github/workflows/create-feature.yml@feature/KAD-2
    with:
      feature-name: ${{ inputs.featureName }}
    secrets: inherit